server:
  port: 8888
spring:
  application:
    name: contacts
  datasource:
    name: test
    #数据库驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接
    url: jdbc:mysql://192.168.1.220:3309/webapi?useSSL=false
    #数据库用户名
    username: apiuser
    #数据库用户密码
    password: Ctm56@Long
    #连接池类型，druid连接池springboot暂无法默认支持，需要自己配置bean
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    #连接池初始化连接数量
    initialSize: 1
    #最小空闲数
    minIdle: 3
    #连接池最大活跃连接数
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #连接是否有效的查询语句
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    removeAbandoned: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # SQL监控后台登录用户名
    druidLoginName: admin
    # SQL监控后台登录用户密码
    druidPassword: admin


mybatis:
  #sql文件配置
  mapper-locations: classpath*:mapper/*.xml
  #实体类设置别名
  type-aliases-package: com.wcw.contacts.entity
  #mybatis.config-location配置sqlMap-config
  #config-location: classpath:/mybatis-config.xml

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  config: classpath:logConfigs/logback.xml